canonical: http://hl7.org/fhir/us/vrdr
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: vrdr
name: VRDR
status: draft
version: 1.2.0
dependencies:
  hl7.fhir.us.core: 3.1.0
  hl7.fhir.us.odh: 1.0.0
menu:
  Home: index.html
  Artifacts: artifacts.html
